version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "8000:8000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    networks: 
      - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: JanssenSBD
      MONGODB_INITDB_ROOT_PASSWORD: janssen
    networks: 
      - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
