version: "3"
services:
  web:
    build: ./frontend
    #Communication avec l'API
    depends_on:
      - api
    ports:
      - "8000:80"
    networks:
      - backend
  api:
    build: ./backend
    #Une requête vers mongo
    depends_on:
      - mongo
    ports:
      - "8001:83"
    networks: 
      - backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/mongo
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: JanssenSBD
      MONGODB_INITDB_ROOT_PASSWORD: janssen
    networks: 
      - backend

networks:
  backend:

volumes: 
  mongodb:
